extends:
  - mizchi
plugins:
  - mutation
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules # defaults to 'node_modules', but...
        - src
rules:
  import/prefer-default-export: 0
  # mutation
  mutation/no-mutation:
    - 2
    -
      execptions:
        this
        exports
